block_list = [
    "item.itemLock.",

    "item.banner.border.",
    "item.banner.bricks.",
    "item.banner.circle.",
    "item.banner.creeper.",
    "item.banner.cross.",
    "item.banner.curly_border.",
    "item.banner.diagonal_left.",
    "item.banner.diagonal_right.",
    "item.banner.diagonal_up_left.",
    "item.banner.diagonal_up_right.",
    "item.banner.flower.",
    "item.banner.globe.",
    "item.banner.gradient.",
    "item.banner.gradient_up.",
    "item.banner.half_horizontal.",
    "item.banner.half_horizontal_bottom.",
    "item.banner.half_vertical.",
    "item.banner.half_vertical_right.",
    "item.banner.mojang.",
    "item.banner.piglin.",
    "item.banner.rhombus.",
    "item.banner.skull.",
    "item.banner.small_stripes.",
    "item.banner.square_bottom_left.",
    "item.banner.square_bottom_right.",
    "item.banner.square_top_left.",
    "item.banner.square_top_right.",
    "item.banner.straight_cross.",
    "item.banner.stripe_bottom.",
    "item.banner.stripe_center.",
    "item.banner.stripe_downleft.",
    "item.banner.stripe_downright.",
    "item.banner.stripe_left.",
    "item.banner.stripe_middle.",
    "item.banner.stripe_right.",
    "item.banner.stripe_top.",
    "item.banner.triangle_bottom.",
    "item.banner.triangle_top.",
    "item.banner.triangles_bottom.",
    "item.banner.triangles_top.",

    "item.tropicalColor",
    "item.tropicalBody",
    "item.tropicalSchool",

    "item.spawn_egg.entity.",

    "tile.netherreactor."
]